### train configuraton

exp_dir: exp/MFA-Conformer-ASTP-emb192-fbank80-num_frms300-aug0.6-spFalse-saFalse-ArcMargin-Adam-epoch150
gpus: "[0,1]"
num_avg: 10

seed: 42
num_epochs: 40
save_epoch_interval: 1 # save model every 5 epochs
log_batch_interval: 100 # log every 100 batchs

dataloader_args:
  batch_size: 64
  num_workers: 16
  pin_memory: True
  prefetch_factor: 4
  drop_last: False

dataset_args:
  shuffle: True
  shuffle_args:
    shuffle_size: 2500
  speed_perturb: True
  num_frms: 200
  aug_prob: 0.6 # prob to add reverb & noise aug per sample
  fbank_args:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 1.0
  spec_aug: False
  spec_aug_args:
    num_t_mask: 1
    num_f_mask: 1
    max_t: 10
    max_f: 8
    prob: 0.0

model: MFA_Conformer
model_init: null
model_args:
  feat_dim: 80
  embed_dim: 192
  pooling_func: 'ASTP'
projection_args:
  project_type: 'arc_margin' # add_margin, arc_margin, sphere, softmax
  scale: 32.0
  easy_margin: False

margin_scheduler: MarginScheduler
margin_update:
  initial_margin: 0.0
  final_margin: 0.2
  increase_start_epoch: 2
  fix_start_epoch: 5
  update_margin: True
  increase_type: 'exp'  # exp, linear

loss: CrossEntropyLoss
loss_args: { }

optimizer: Adam
optimizer_args:
  lr: 0.01
  weight_decay: 0.000001

scheduler: ExponentialDecrease
scheduler_args:
  initial_lr: 0.01
  final_lr: 0.00001
  warm_up_epoch: 3
